#!/bin/sh

uci set fstab.@mount[0].target='/overlay'
uci set fstab.@mount[0].device='/dev/sda1'
uci set fstab.@mount[0].fstype='ext4'
uci set fstab.@mount[0].options='rw,noatime'
uci set fstab.@mount[0].enabled='1'


uci add fstab mount

uci set fstab.@mount[-1].target='/mnt/data'
uci set fstab.@mount[-1].device='/dev/sda5'
uci set fstab.@mount[-1].fstype='ext4'
uci set fstab.@mount[-1].options='rw,noatime'
uci set fstab.@mount[-1].enabled='1'


uci commit fstab

/etc/init.d/fstab enable

exit 0
