name: Build WR8305RT OpenWrt Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENWRT_VERSION: "22.03.5"
      TARGET: "ramips"
      SUBTARGET: "mt7620"
      PROFILE: "zbtlink_zbt-wr8305rt"

    steps:

      - name: Checkout source
        uses: actions/checkout@v4


      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y wget tar xz-utils


      - name: Check files
        run: |
          echo "Checking custom files..."

          if [ ! -f files/etc/uci-defaults/99-extroot ]; then
            echo "ERROR: 99-extroot missing"
            exit 1
          fi

          echo "Custom files OK"
          find files -type f


      - name: Download ImageBuilder
        run: |

          IB_NAME="openwrt-imagebuilder-${OPENWRT_VERSION}-${TARGET}-${SUBTARGET}.Linux-x86_64.tar.xz"

          URL="https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET}/${SUBTARGET}/${IB_NAME}"

          echo "Download:"
          echo $URL


          wget -O "$IB_NAME" "$URL"


          echo "Extract..."

          tar -xJf "$IB_NAME"


      - name: Find ImageBuilder
        run: |

          IB_DIR=$(find . -maxdepth 1 \
          -type d \
          -name "openwrt-imagebuilder-*" \
          | head -n1)


          if [ -z "$IB_DIR" ]; then
            echo "ImageBuilder not found"
            exit 1
          fi


          echo "IB_DIR=$IB_DIR" >> $GITHUB_ENV


      - name: Build firmware
        run: |

          cd "$IB_DIR"


          echo "Check profile..."

          make info | grep zbt || true


          echo "Building..."


          make image \
          PROFILE="${PROFILE}" \
          PACKAGES="
          kmod-usb-core
          kmod-usb2
          kmod-usb-storage
          kmod-scsi-core
          kmod-fs-ext4
          kmod-fs-vfat
          block-mount
          mount-utils
          " \
          FILES="../files"


      - name: Collect firmware
        run: |

          mkdir -p output


          cp -rv \
          $IB_DIR/bin/targets/*/* \
          output/


          echo "Firmware output:"
          ls -lh output


      - name: Upload firmware
        uses: actions/upload-artifact@v4

        with:
          name: WR8305RT-OpenWrt-22.03.5
          path: output
